import Config

# Configure your database
config :personal_drive_api, PersonalDriveApi.Repo,
  database: Path.expand("../personal_drive_api_dev.db", Path.dirname(__ENV__.file)),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :personal_drive_api, PersonalDriveApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lrPY80pwvtR596joLdnbxYz+Zx4Bt3q1EN8QRTlBDtUjSTnOehc5FA1i95h/+DtO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :personal_drive_api, PersonalDriveApiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/personal_drive_api_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :personal_drive_api, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# R2 Cloudflare Storage Configuration (dev)
config :ex_aws,
  access_key_id: System.get_env("R2_ACCESS_KEY_ID", "test"),
  secret_access_key: System.get_env("R2_SECRET_ACCESS_KEY", "test"),
  region: System.get_env("R2_REGION", "auto"),
  s3: [
    host: System.get_env("R2_HOST", "localhost:9000"),
    scheme: "http://"
  ]

config :personal_drive_api, :r2,
  bucket: System.get_env("R2_BUCKET", "personal-drive"),
  public_url: System.get_env("R2_PUBLIC_URL", "http://localhost:9000/personal-drive")

# Resend Configuration (dev - uses test key or set RESEND_API_KEY)
config :personal_drive_api, :resend,
  api_key: System.get_env("RESEND_API_KEY", "re_test_123456789")
